version: '3.9'
services:
  web:
    build:
      context: .
      args:
        uid: '${UID}'
    container_name: web
    environment:
      - 'APACHE_RUN_USER=#${UID}'
      - 'APACHE_RUN_GROUP=#${UID}'
    volumes:
      - '.:/var/www/html'
      - './docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini'
    ports:
      - '${HTTP_PORT:-80}:80'
    networks:
      backend:
        aliases:
          - web

  mailhog:
    image: mailhog/mailhog
    ports:
      - '${DOCKER_MAILHOG_PORT:-8025}:8025'

  db:
    image: 'mysql:8.0'
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: db
    volumes:
      - './run/var:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=securerootpassword'
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: network
